---
title: "Kanika Kolpe"
Date: 3/2/2026
format: html
---

##Introduction
This is the metadata from my first field collection for my project. It includes the sample ID, date, desert, site ID, longitude, latitude, county, state, time, and elevation. 

## Data (where you import the data and view it, to see if it is tidy)
I put my data in the Raw Data folder 
```{r}
library(readr)
site_metadata <- read_csv("Data/Raw Data/site_metadata.csv")
View(site_metadata)

```


##Analysis (where you comment on whether or not it is tidy and if it has primary and foreign keys)

My data is not tidy. 
My data does not have any primary or foreign keys because it is metadata so it includes everything. 


##Conclusion (a short summary)
I have analyzed my data and come to the conclusion that it is not tidy because there are a lot of rows that are completely empty. Other than the empty rows, I do believe that my columns are a bit redundant due to having 5 columns dedicated for coordinates. The reason my data does not have any primary or foreign keys is because it is metadata so it includes everything. There isn't any other data to reference due to the fact that this is the only data I currently have. 