---
title: "a05"
format: html
---

```{r, warning = FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(forcats) # makes working with factors easier
library(ggplot2)
library(leaflet) # interactive maps
library(DT) # interactive tables
library(scales) # scale functions for visualization
library(janitor) # expedite cleaning and exploring data
library(viridis) # colorblind friendly color palette
```

```{r}
# read in data from the data directory after manually downloading data 
delta_visits_raw <- read_csv(here::here("data/Socioecological_monitoring_data.csv"))

## Check out column names

colnames(delta_visits_raw)

## Peak at each column and class
glimpse(delta_visits_raw)

## From when to when
range(delta_visits_raw$Date)

## Which time of day?
unique(delta_visits_raw$Time_of_Day)
```

```{r}
delta_visits <- delta_visits_raw %>% 
    janitor::clean_names()
colnames(delta_visits)
```

```{r}
visits_long <- delta_visits %>% 
    pivot_longer(cols = c(sm_boat, med_boat, lrg_boat, bank_angler, scientist, cars),
                 names_to = "visitor_type",
                 values_to = "quantity") %>%
    rename(restore_loc = eco_restore_approximate_location) %>% 
    select(-notes)

## Checking the outcome
head(visits_long)
```

```{r}
daily_visits_loc <- visits_long %>%
    group_by(restore_loc, date, visitor_type) %>% 
    summarise(daily_visits = sum(quantity))
    
head(daily_visits_loc)
```

```{r}
## Option 1 - data and mapping called in the ggplot() function
ggplot(data = daily_visits_loc,
       aes(x = restore_loc, y = daily_visits)) +
    geom_col()


## Option 2 - data called in ggplot function; mapping called in geom
ggplot(data = daily_visits_loc) +
    geom_col(aes(x = restore_loc, y = daily_visits))


## Option 3 - data and mapping called in geom
ggplot() +
    geom_col(data = daily_visits_loc,
             aes(x = restore_loc, y = daily_visits))
```

```{r}
ggplot(data = daily_visits_loc,
       aes(x = restore_loc, y = daily_visits)) +
    geom_col()
```

```{r}
daily_visits_loc %>%
    separate(date, c("year", "month", "day"), sep = "-") %>%
    filter(daily_visits < 30,
           visitor_type %in% c("sm_boat", "med_boat", "lrg_boat")) %>%
    ggplot(aes(x = visitor_type, y = daily_visits)) +
    geom_boxplot()
```


```{r}
daily_visits_loc %>%
    separate(date, c("year", "month", "day"), sep = "-") %>%
    filter(daily_visits < 30,
           visitor_type %in% c("sm_boat", "med_boat", "lrg_boat")) %>%
    ggplot(aes(x = visitor_type, y = daily_visits)) +
    geom_violin()
```


```{r}
daily_visits_loc %>%
    filter(restore_loc == "Decker Island",
           visitor_type == "med_boat") %>%
    ggplot(aes(x = date, y = daily_visits)) +
    geom_line() +
    geom_point()
```


```{r}
ggplot(data = daily_visits_loc,
       aes(x = restore_loc, y = daily_visits,
           fill = "blue")) +
    geom_col()
```

```{r}
ggplot(data = daily_visits_loc,
       aes(x = restore_loc, y = daily_visits)) +
    geom_col(fill = "blue")
```

```{r}
ggplot(data = daily_visits_loc,
       aes(x = restore_loc, y = daily_visits,
           fill = visitor_type)) +
    geom_col()
```


```{r}
ggplot(data = daily_visits_loc,
       aes(y = restore_loc, x = daily_visits, fill = visitor_type)) +
    geom_col() +
    labs(x = "Number of Visits",
         y = "Restoration Location",
         fill = "Type of Visitor",
         title = "Total Number of Visits to Delta Restoration Areas by visitor type",
         subtitle = "Sum of all visits during July 2017 and March 2018") +
    theme_bw()
```

```{r}
ggplot(data = daily_visits_loc,
       aes(y = restore_loc, x = daily_visits, fill = visitor_type)) +
    geom_col() +
    labs(x = "Number of Visits",
         y = "Restoration Location",
         fill = "Type of Visitor",
         title = "Total Number of Visits to Delta Restoration Areas by visitor type",
         subtitle = "Sum of all visits during study period") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.ticks.y = element_blank()) 
```

```{r}
my_theme <- theme_bw(base_size = 16) +
    theme(legend.position = "bottom",
          axis.ticks.y = element_blank())
```

```{r}
ggplot(data = daily_visits_loc,
       aes(y = restore_loc, x = daily_visits, fill = visitor_type)) +
    geom_col() +
    labs(x = "Number of Visits",
         y = "Restoration Location",
         fill = "Type of Visitor",
         title = "Total Number of Visits to Delta Restoration Areas by visitor type",
         subtitle = "Sum of all visits during study period") +
    my_theme
```

```{r}
daily_visits_totals <- daily_visits_loc %>% 
    group_by(restore_loc) %>%
    mutate(n = sum(daily_visits)) %>% 
    ungroup() %>%
    mutate(restore_loc = fct_reorder(restore_loc, n))

head(daily_visits_totals)
```

```{r}
levels(daily_visits_totals$restore_loc) ### not alphabetical any more!
```

```{r}
ggplot(data = daily_visits_totals,
       aes(x = daily_visits, y = restore_loc,
           fill = visitor_type)) +
    geom_col() +
    labs(x = "Number of Visits",
         y = "Restoration Location",
         fill = "Type of Visitor",
         title = "Total Number of Visits to Delta Restoration Areas by visitor type",
         subtitle = "Sum of all visits during study period") +
    scale_x_continuous(breaks = seq(0,120, 20), expand = c(0,0)) +
    my_theme
```

```{r}
daily_visits_totals <- daily_visits_loc %>% 
    group_by(restore_loc) %>%
    mutate(n = sum(daily_visits)) %>% 
    ungroup() %>%
    mutate(restore_loc = fct_reorder(restore_loc, desc(n)))

ggplot(data = daily_visits_totals,
       aes(x = daily_visits, y = restore_loc,
           fill = visitor_type)) +
    geom_col() +
    labs(x = "Number of Visits",
         y = "Restoration Location",
         fill = "Type of Visitor",
         title = "Total Number of Visits to Delta Restoration Areas by visitor type",
         subtitle = "Sum of all visits during study period") +
    scale_x_continuous(breaks = seq(0,120, 20), expand = c(0,0)) +
    my_theme
```

```{r}
ggplot(data = daily_visits_totals,
       aes(x = daily_visits, y = restore_loc,
           fill = visitor_type)) +
    geom_col() +
    scale_fill_viridis_d() +
    labs(x = "Number of Visits",
         y = "Restoration Location",
         fill = "Type of Visitor",
         title = "Total Number of Visits to Delta Restoration Areas by visitor type",
         subtitle = "Sum of all visits during study period") +
    scale_x_continuous(breaks = seq(0,120, 20), expand = c(0,0)) +
    my_theme
```

```{r}
ggsave("figures/visit_restore_site_delta.jpg", width = 12, height = 6, units = "in")
```

```{r}
facet_plot <- ggplot(data = daily_visits_totals,
       aes(x = visitor_type, y = daily_visits,
           fill = visitor_type)) +
    geom_col() +
    facet_wrap(~restore_loc,
               scales = "free_y",
               ncol = 5,
               nrow = 2) +
    scale_fill_viridis_d() +
    labs(x = "Type of visitor",
         y = "Number of Visits",
         title = "Total Number of Visits to Delta Restoration Areas",
         subtitle = "Sum of all visits during study period") +
    theme_bw() +
    theme(legend.position = "bottom",
          axis.ticks.x = element_blank(),
          axis.text.x = element_blank())

facet_plot
```

```{r}
ggsave("figures/visit_restore_site_facet.jpg", plot = facet_plot, width = 12, height = 8, units = "in")
```

```{r}
locations <- visits_long %>%
    distinct(restore_loc, .keep_all = TRUE) %>%
    select(restore_loc, latitude, longitude)

head(locations)
```

```{r}
datatable(locations)
```

```{r}
leaflet(locations) %>%
    addTiles() %>%
    addMarkers(
        lng = ~ longitude,
        lat = ~ latitude,
        popup = ~ restore_loc
    )
```

```{r}
leaflet(locations) %>%
    addProviderTiles(providers$Esri.WorldTopoMap) %>%
    addCircleMarkers(
        lng = ~ longitude,
        lat = ~ latitude,
        popup = ~ restore_loc,
        radius = 5,
        # set fill properties
        fillColor = "salmon",
        fillOpacity = 1,
        # set stroke properties
        stroke = TRUE,
        weight = 0.5,
        color = "white",
        opacity = 1)
```

```{r}
leaflet(locations) %>%
    addProviderTiles(providers$Esri.WorldImagery) %>%
    addProviderTiles(providers$CartoDB.PositronOnlyLabels) %>%
    addCircleMarkers(
        lng = ~ longitude,
        lat = ~ latitude,
        popup = ~ restore_loc,
        radius = 5,
        # set fill properties
        fillColor = "salmon",
        fillOpacity = 1,
        # set stroke properties
        stroke = TRUE,
        weight = 0.5,
        color = "white",
        opacity = 1)
```


